media:
  input: assets
  output: /assets

content:
  - name: eboard_data
    label: Executive Board Data
    type: file
    path: data/eboard.json
    fields:
      - name: members
        label: Members
        type: list
        fields:
          - name: name
            label: Name
            type: string
          - name: role
            label: Role
            type: string
          - name: major
            label: Major
            type: string
          - name: image
            label: Photo
            type: image

  - name: links_data
    label: Links Page Data
    type: file
    path: data/links.json
    fields:
      - name: links
        label: Links List
        type: list
        fields:
          - name: type
            label: Type
            type: string
          - name: title
            label: Title
            type: string
          - name: url
            label: URL
            type: string
          - name: text
            label: Text
            type: string
          - name: description
            label: Description
            type: string

  - name: sponsors
    label: Sponsors
    type: file
    path: data/sponsors.json
    fields:
      - name: sponsors
        label: Sponsors List
        type: list
        fields:
          - name: name
            label: Sponsor Name
            type: string
            required: true
          - name: logo
            label: Logo Image (Optional)
            type: image
          - name: color
            label: Logo Box Background Color
            type: color
            default: "#ffffff"
          - name: text_color
            label: Logo Text Color
            type: color
            default: "#000000"
          - name: description
            label: Description
            type: string
            required: true
          - name: discount_code
            label: Discount Code (Optional)
            type: string