backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "eboard_data"
    label: "E-Board Data"
    files:
      - file: "data/eboard.json"
        label: "E-Board Members"
        name: "eboard"
        format: "json"
        fields:
          - label: "Members"
            name: "members"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }
              - { label: "Bio", name: "bio", widget: "text", required: false }
              - { label: "Photo", name: "image", widget: "image", required: false }

  - name: "links_data"
    label: "Links Page Data"
    files:
      - file: "data/links.json"
        label: "Links"
        name: "links_page"
        format: "json"
        fields:
          - label: "Links List"
            name: "links"
            widget: "list"
            fields:
              - { label: "Type", name: "type", widget: "string", required: false }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Text", name: "text", widget: "string", required: false }
              - { label: "Description", name: "description", widget: "text", required: false }